<div class="content">   
    <!-- <ul class="content-tabs  tabs ed-grid ed-grid s-grid-4 m-grid-4 lg-grid-4 xl-grid-4 tabs-fixed-width tab-demo z-depth-1 gap-0">
        <li class="tab tab-courses"><a  class="tab__link  active"  href="#courses"><h1>Cursos - Modalidad Presencial</h1> <span>Cursos</span> <img class="tab__img-couser" src="<?php //echo get_bloginfo('template_directory').'/assets/img/woman-course.png';?>" alt="cursos" ></a></li> 
        <li class="tab tab-diplomas "><a class="tab__link  " href="#diplomas"> <h1>Diplomas de Especialización</h1> <span>Diplomas</span> <img src=" <?php // echo get_bloginfo('template_directory').'/assets/img/diploma_tab.png';?>" alt="diplomas" > </a></li> 
        <li class="tab tab-congress" ><a class="tab__link " href="#congresses"> <h1>Congresos Nacionales e Internacionales</h1> <span>Congresos</span><img  class="tab__img-congress" src="<?php // echo get_bloginfo('template_directory').'/assets/img/conferencia-man.png';?>" alt="congresos" ></a> 
        <li class="tab tab-inhouse " ><a class="tab__link " href="#inhouse"> <h1>Capacitación a la Medida - Cursos In-House</h1> <span>In-HOUSE</span><img  class="tab__img-congress" src="<?php // echo get_bloginfo('template_directory').'/assets/img/inhouse.png';?>" alt="cursos in-house" ></a> 
    </ul>  -->
<ul class="content-tabs  tabs ed-grid ed-grid s-grid-2 m-grid-2 lg-grid-4 xl-grid-4 tabs-fixed-width tab-demo z-depth-1 gap-2   ">
        <li class="tab tab-courses"><a  class="tab__link  active"  href="#courses"> <picture> <img class="tab__img-couser" src="<?php echo get_bloginfo('template_directory').'/assets/img/cursos-tab-bg.png';?>" alt="cursos" ><svg class=""><use href="<?php echo get_bloginfo('template_directory').'/assets/img/icons.svg#courses'; ?>"></svg> <span>Cursos</span> </picture><h1>Cursos - Modalidad Presencial</h1>  </a></li> 
        <li class="tab tab-diplomas "><a class="tab__link  " href="#diplomas">   <picture> <img src=" <?php echo get_bloginfo('template_directory').'/assets/img/diplomas-tab-bg.png';?>" alt="diplomas" ><svg class=""><use href="<?php echo get_bloginfo('template_directory').'/assets/img/icons.svg#diplomas'; ?>"></svg> <span>Diplomas</span> </picture> <h1>Diplomas de Especialización</h1>   </a></li> 
        <li class="tab tab-congress" ><a class="tab__link " href="#congresses">  <picture> <img  class="tab__img-congress" src="<?php echo get_bloginfo('template_directory').'/assets/img/congresos-tab-bg.png';?>" alt="congresos" ><svg class=""><use href="<?php echo get_bloginfo('template_directory').'/assets/img/icons.svg#congresses'; ?>"></svg> <span>Congresos</span> </picture><h1>Congresos Nacionales e Internacionales</h1> </a> 
        <li class="tab tab-inhouse " ><a class="tab__link " href="#inhouse">  <picture> <img  class="tab__img-congress" src="<?php echo get_bloginfo('template_directory').'/assets/img/inhouse-tab-bg.png';?>" alt="cursos in-house" ><svg class=""><use href="<?php echo get_bloginfo('template_directory').'/assets/img/icons.svg#inhouse'; ?>"></svg> <span>In-House</span> </picture><h1>Capacitación a la Medida - Cursos In-House</h1> </a> 
    </ul> 
</div>